import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const sections = [
    {
      name: 'Frontend',
      color: '#EF767A',
      paths: [
        {
          name: 'Desktop',
          blocks: [
            { name: 'Browser API', variant: 'goodtoknow' },
            {
              name: 'Html',
              description:
                "Html is essential for getting into web. P.S. IT'S NOT A PROGRAMMING LANGUAGE",
              links: [
                'https://htmlacademy.org/',
                'https://www.w3schools.com/html/',
                'https://www.youtube.com/watch?v=a_iQb1lnAEQ',
              ],
              variant: 'essential',
            },
            { name: 'Css' },
            { name: 'Javascript' },
          ],
        },
        { name: 'Web' },
      ],
    },
    { name: 'Backend', color: '#456990' },
    { name: 'Marketing', color: '#EEB868' },
  ];

  const [isOpened, setIsOpened] = useState(true);
  const [currentBlock, setCurrentBlock] = useState<any>();

  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>CenterInvest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav className="w-full px-10 py-5 text-3xl text-white bg-green-600">
          <p>Центр-Навыки</p>
        </nav>
      </header>
      <main className={styles.mainBlock}>
        <div className="flex justify-center w-full gap-5 mt-20">
          {sections.map((sec) => (
            <div key={sec.name}>
              <div
                className="p-20 text-3xl font-semibold rounded-full shadow-md cursor-pointer"
                style={{ backgroundColor: sec.color }}
              >
                {sec.name}
              </div>
            </div>
          ))}
        </div>
        <div className={styles.subSection}>
          Дополнительная информация:
          {currentBlock && (
            <div>
              <p>{currentBlock.description}</p>

              <div>
                {(currentBlock.links || []).map((link: string) => (
                  <p key={link}>{link}</p>
                ))}
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
